In [1]:
import numpy as np
import pandas as pd
min_support=input("Please enter min support : ")
min_support=float(min_support)
if min_support > 1:
    min_support=min_support/5822
min_convidence=input("Please enter min convidence : ")
min_convidence=float(min_convidence)
# min_support = 0.2
# min_convidence = 0.5

Please enter min support : 0.2
Please enter min convidence : 0.5


In [2]:
read_file = pd.read_csv ("C:/Users/Mahmoud Kholief/Desktop/big data project/ticdata2000.txt",delimiter="\t",header=None)
read_file

0   1   2   3   4   5   6   7   8   9   ...  76  77  78  79  80  81  82  \
0     33   1   3   2   8   0   5   1   3   7  ...   0   0   0   1   0   0   0   
1     37   1   2   2   8   1   4   1   4   6  ...   0   0   0   1   0   0   0   
2     37   1   2   2   8   0   4   2   4   3  ...   0   0   0   1   0   0   0   
3      9   1   3   3   3   2   3   2   4   5  ...   0   0   0   1   0   0   0   
4     40   1   4   2  10   1   4   1   4   7  ...   0   0   0   1   0   0   0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
5817  36   1   1   2   8   0   6   1   2   1  ...   0   0   0   1   0   0   0   
5818  35   1   4   4   8   1   4   1   4   6  ...   0   0   0   1   0   0   0   
5819  33   1   3   4   8   0   6   0   3   5  ...   0   0   0   1   0   0   0   
5820  34   1   3   2   8   0   7   0   2   7  ...   0   0   0   0   0   0   0   
5821  33   1   3   3   8   0   6   1   2   7  ...   0   0   0   0   0   0   0   

      83  84  85  
0      0   0   0  
1      0   0   0  
2      0   0   0  
3      0   0   0  
4      0   0   0  
...   ..  ..  ..  
5817   0   0   0  
5818   0   0   0  
5819   0   0   1  
5820   0   0   0  
5821   0   0   0  

[5822 rows x 86 columns]

In [3]:
# our_data=read_file.iloc[:, 30:30+12]
our_data=read_file[[i for i in range (30,30+12)]]
our_data

30  31  32  33  34  35  36  37  38  39  40  41
0      8   8   0   1   8   1   0   4   5   0   0   4
1      7   7   1   2   6   3   2   0   5   2   0   5
2      2   7   0   2   9   0   4   5   0   0   0   3
3      4   9   0   0   7   2   1   5   3   0   0   4
4      5   6   2   1   5   4   0   0   9   0   0   6
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
5817   0   5   1   3   5   4   4   3   3   0   0   3
5818   6   6   1   2   6   3   0   9   0   0   0   4
5819   2   4   0   5   8   1   5   3   1   1   0   3
5820   7   5   4   0   9   0   0   5   4   0   0   4
5821   4   5   2   3   6   3   2   5   2   1   0   3

[5822 rows x 12 columns]

In [4]:
names = {"MHKOOP":"Home owners","MAUT1":"1 car","MAUT2":"2 cars","MAUT0":"No car","MZFONDS":"National Health Service","MZPART":"Private health insurance","MINKM30":"Income < 30.000","MINK3045":"Income 30-45.000","MINK4575":"Income 45-75.000","MINK7512":"Income 75-122.000","MINK123M":"Income >123.000","MINKGEM":"Average income"}
# names

In [5]:
long_names=[names[i] for i in names]
# long_names

In [6]:
our_data.columns=long_names
our_data

Home owners  1 car  2 cars  No car  National Health Service  \
0               8      8       0       1                        8   
1               7      7       1       2                        6   
2               2      7       0       2                        9   
3               4      9       0       0                        7   
4               5      6       2       1                        5   
...           ...    ...     ...     ...                      ...   
5817            0      5       1       3                        5   
5818            6      6       1       2                        6   
5819            2      4       0       5                        8   
5820            7      5       4       0                        9   
5821            4      5       2       3                        6   

      Private health insurance  Income < 30.000  Income 30-45.000  \
0                            1                0                 4   
1                            3                2                 0   
2                            0                4                 5   
3                            2                1                 5   
4                            4                0                 0   
...                        ...              ...               ...   
5817                         4                4                 3   
5818                         3                0                 9   
5819                         1                5                 3   
5820                         0                0                 5   
5821                         3                2                 5   

      Income 45-75.000  Income 75-122.000  Income >123.000  Average income  
0                    5                  0                0               4  
1                    5                  2                0               5  
2                    0                  0                0               3  
3                    3                  0                0               4  
4                    9                  0                0               6  
...                ...                ...              ...             ...  
5817                 3                  0                0               3  
5818                 0                  0                0               4  
5819                 1                  1                0               3  
5820                 4                  0                0               4  
5821                 2                  1                0               3  

[5822 rows x 12 columns]

In [7]:
#kollo lists
def support(names,numbers):
    our_data2=our_data.copy()
    for i,j in zip(names,numbers):
        our_data2=our_data2.loc[our_data2[i]==j]
#     print(our_data2)
    return our_data2.count()[0]/5822

In [8]:
#kollo lists
def convidence(names1,numbers1,names2,numbers2):
    return (support(np.concatenate((names1,names2)),np.concatenate((numbers1,numbers2)))/support(names1,numbers1))

In [9]:
#kollo lists
def lift(names1,numbers1,names2,numbers2):
    return (support(np.concatenate((names1,names2)),np.concatenate((numbers1,numbers2)))/(support(names1,numbers1)*support(names2,numbers2)))

#kollo lists
def leverage(names1,numbers1,names2,numbers2):
    return (support(np.concatenate((names1,names2)),np.concatenate((numbers1,numbers2)))-(support(names1,numbers1)*support(names2,numbers2)))

In [10]:
def printt(list1,list2):
    text=""
    for i,j in zip(list1,list2):
        text+=i+" ("+str(j)+") , "
    return text[:-2]

In [11]:
index=[]
for i in long_names:
    unique=our_data[i].unique()
    index.append(sorted(unique))
print("index are : ")
index

index are : 


[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 7, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [12]:
import itertools
all_combinations = []
for r in range(1,(len(long_names) + 1)):
    combinations_object = itertools.combinations(long_names, r)
    combinations_list = np.array(list(combinations_object))
#     print(combinations_list)
    all_combinations.append(combinations_list)

# print(len(all_combinations))

In [13]:
s=1
for i in all_combinations[0:]:
    lists1=[]
    lists2=[]
    index2=[[],[],[],[],[],[],[],[],[],[],[],[]]
    for j in i:
        #j=['Home owners' '1 car' '2 car']
#         print(j)
        array=[]
        for k in j:
            l=long_names.index(k)
            array.append(index[l])
#         print(array)
        n = np.array(list(itertools.product(*array)))
        for m in n:
#             print(j)
#             print(m)
            supports=support(j,m)
            if supports>min_support:
                lists1.append(j)
                lists2.append(m)
                for p,o in zip(j,m):
                    l=long_names.index(p)
                    if o not in index2[l]:
                        index2[l].append(o)
    print(f"index after ( {s}-itemsets ) with support >= min_support: ")
    print(index2)
    print("")
    s+=1
#     print(len(lists1))
    if len(lists1)!=0:
        listsx=lists1
        listsy=lists2
        index=index2
    else:
        break

index after ( 1-itemsets ) with support >= min_support: 
[[], [5, 6, 7], [0, 1, 2], [0, 2], [7], [2], [0], [4], [2, 3], [0, 1], [0], [3, 4]]

index after ( 2-itemsets ) with support >= min_support: 
[[], [6, 7], [0, 1, 2], [0, 2], [7], [2], [], [], [], [0], [0], [3, 4]]

index after ( 3-itemsets ) with support >= min_support: 
[[], [], [0], [], [7], [2], [], [], [], [0], [0], [3]]

index after ( 4-itemsets ) with support >= min_support: 
[[], [], [], [], [], [], [], [], [], [], [], []]



In [14]:
print(np.array(listsx))

[['2 cars' 'Income 75-122.000' 'Income >123.000']
 ['National Health Service' 'Private health insurance' 'Income >123.000']
 ['Income 75-122.000' 'Income >123.000' 'Average income']]


In [15]:
print(np.array(listsy))

[[0 0 0]
 [7 2 0]
 [0 0 3]]


In [16]:
print(index)

[[], [], [0], [], [7], [2], [], [], [], [0], [0], [3]]


In [17]:
for i,j in zip(listsx,listsy):
    i=list(i)
    j=list(j)
#     print(i)
#     print(j)
    print("")
    combinations1 = []
    combinations2 = []
    for r in range(1,(len(i))):
        combinations_object1 = itertools.combinations(i, r)
        combinations_object2 = itertools.combinations(j, r)
        combinations_list1 = np.array(list(combinations_object1))
        combinations_list2 = np.array(list(combinations_object2))
    #     print(combinations_list)
        combinations1.append(combinations_list1)
        combinations2.append(combinations_list2)

    # print(len(combinations1))
    # print(len(combinations2))
    for k,l in zip(combinations1,combinations2):    # m,n >>>>> q,w
        for m,n in zip(k,l):
#             print(m)
#             print(n)
            q=i.copy()
            w=j.copy()
            lallo=[]
            for o in m:
                e=q.index(o)
                del q[e]
                del w[e]
#             for e in lallo:
#                 del q[e]
#                 del w[e]
#             print(q)
#             print(w)
            if convidence(m,n,q,w)>=min_convidence:
                print(printt(m,n)+"          >>>          "+printt(q,w))
                print(f"convidence = {convidence(m,n,q,w)}")
                print(f"lift = {lift(m,n,q,w)}")
                print(f"leverage = {leverage(m,n,q,w)}")
                print("")
                print("")


2 cars (0)           >>>          Income 75-122.000 (0) , Income >123.000 (0) 
convidence = 0.6477885652642935
lift = 1.2308828416999729
leverage = 0.0386941889120751


2 cars (0) , Income 75-122.000 (0)           >>>          Income >123.000 (0) 
convidence = 0.9584996009577016
lift = 1.138854015668518
leverage = 0.025151343752201627


2 cars (0) , Income >123.000 (0)           >>>          Income 75-122.000 (0) 
convidence = 0.7195925704014381
lift = 1.2906555591118831
leverage = 0.04645570804825774



National Health Service (7)           >>>          Private health insurance (2) , Income >123.000 (0) 
convidence = 0.8855062872270021
lift = 3.8530774321641297
leverage = 0.17017263908879965


Private health insurance (2)           >>>          National Health Service (7) , Income >123.000 (0) 
convidence = 0.8855062872270021
lift = 3.8530774321641297
leverage = 0.17017263908879965


National Health Service (7) , Private health insurance (2)           >>>          Income >123.000 (0)